name: push-to-production

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  checkout-and-build:
    runs-on: self-hosted
    steps:
      
      - name: checkout
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: True
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker_repo:latest
  pull-and-run :
    runs-on: self-hosted
    steps:
    
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: pull
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/docker_repo:latest

      - name: stop-containers
        run: docker stop $(docker ps -a -q)
      
      - name: run
        run: docker run -d -p 80:80 -e discord_api_key=${{ secrets.DISCORD_BOT_API_KEY }} lihanwu/docker_repo:latest

