name: push-to-production

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  update-static-content:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
